# Generated by Django 5.1.5 on 2025-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject2', '0002_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephonemodel',
            name='case',
            field=models.ManyToManyField(blank=True, null=True, related_name='cases', to='homeproject2.case'),
        ),
    ]
